import Head from 'next/head';

interface IHeadProps {
  title: string;
}

const NextHead = (props: IHeadProps) => {
  const { title } = props;
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default NextHead;
